### ISSUE TITLE
test case -- construction of a table

### ISSUE THREAD

**Issue by hhzl** [herby/silk#4]
How would the test case from ``domite`` which constructs a table look like in ``silk``?

````
testInsertTable
| d tbl tr |
d := self testedClass at: 'html body div#fixture'.
tbl := self testedClass newElement: 'table'.
tr := self testedClass newElement: 'tr'.
tr << ((self testedClass newElement: 'td') << 'A').
tr << ((self testedClass newElement: 'td') << 'B').
tr << ((self testedClass newElement: 'td') << 'C').
tbl << tr.
tr := Domite newElement: 'tr'.
tr << ((Domite newElement: 'td') << 'D').
tr << ((Domite newElement: 'td') << 'E').
tr << ((Domite newElement: 'td') << 'F').
tbl << tr.
d << tbl.
self assertBodyEndsWith: 'table><tr><td>A</td><td>B</td><td>C</td></tr><tr><td>D</td><td>E</td><td>F</td></tr></table></div>'
````

**Comment by herby** [comment]
Hannes Hirzel wrote:
> How would the test case from |domite| which constructs a table look 
> like in |silk|?
>
> |testInsertTable
> | d tbl tr |
> d := self testedClass at: 'html body div#fixture'.
d := 'html body div#fixture' asSilk.
> tbl := self testedClass newElement: 'table'.
tbl := d TABLE.
> tr := self testedClass newElement: 'tr'.
tbl TR
> tr<<  ((self testedClass newElement: 'td')<<  'A').
TD: 'A';
> tr<<  ((self testedClass newElement: 'td')<<  'B').
TD: 'B';
> tr<<  ((self testedClass newElement: 'td')<<  'C').
TD: 'C'.
> tbl<<  tr.
Removed.
> tr := Domite newElement: 'tr'.
tbl TR
> tr<<  ((Domite newElement: 'td')<<  'D').
TD: 'D';
> tr<<  ((Domite newElement: 'td')<<  'E').
TD: 'E';
> tr<<  ((Domite newElement: 'td')<<  'F').
TD: 'F'.
> tbl<<  tr.
Removed.
> d<<  tbl.
Removed.
> self assertBodyEndsWith: 'table><tr><td>A</td><td>B</td><td>C</td></tr><tr><td>D</td><td>E</td><td>F</td></tr></table></div>'
This should be the same. Except you missed '>sentinel<' at
 the beginning.

**Comment by herby** [comment]
BTW this is not an issue.

**Comment by hhzl** [comment]
Thank you. 
The test is in 
https://github.com/herby/silk/pull/8

There are two other tests as well.
