### ISSUE TITLE
test case -- construction of a button with handler

### ISSUE THREAD

**Issue by hhzl** [herby/silk#5]
How do I construct a button and attach a Amber Smalltalk block to it?

**Comment by herby** [comment]
Does not understand "attach block to it". As shown in readne, you can create and add an element by

  parent BUTTON

or with content

  parent BUTTON: content

If you want to just create but not add it, you can do

  Silk BUTTON

but the former is preferred.

Dňa 28. februára 2015 16:06:18 CET používateľ Hannes Hirzel <notifications@github.com> napísal:

**Comment by hhzl** [comment]
With ``block`` I mean a Smalltalk block expression which is executed when the button is pressed.

**Comment by herby** [comment]
on: 'click' bind: aBlock

Dňa 28. februára 2015 18:21:05 CET používateľ Hannes Hirzel <notifications@github.com> napísal:

**Comment by hhzl** [comment]
like this

    (parent BUTTON: 'content') on: 'click' bind: aBlock

?

**Comment by hhzl** [comment]
Yes

       (Silk new BUTTON: 'content') on: 'click' bind: [Transcript show: 'Hello'].

works fine.

**Comment by hhzl** [comment]
And this puts the button into a ``div`` block with the id ``container``.

      ((Silk new DIV: {'id' -> 'container'}) 
          BUTTON: 'content')
              on: 'click' bind: [Transcript show: 'Hello'].

Evaluate in workspace and check with

       Transcript show: document body innerHTML.

**Comment by hhzl** [comment]
Any suggestions why the test 
in https://github.com/hhzl/silk/blob/gh-5/src/Silk-Tests.st
does not work?

````
testDivContainerWithButtons
	| s |
 
	s := Silk new DIV: {'id' -> 'container'}.
	(s BUTTON: 'hello1') on: 'click' bind: [Transcript show: 'Hello1'].
	(s BUTTON: 'hello2') on: 'click' bind: [Transcript show: 'Hello2'].
	(s BUTTON: 'hello3') on: 'click' bind: [Transcript show: 'Hello3'].
	
	
	self assertBodyEndsWith: 
             'div id="fixture">sentinel</div><div id="container"><button>hello1</button><button>hello2</button><button>hello3</button></div>'.
````

**Comment by herby** [comment]
Unless you specifically want to test that `Silk new` appends to body, you should use div with id "fixture" as a place where test should put data. This test must fail in tearDown if you use same tearDown as the other tests, as it check that last child in body in indeed that div (and it's good that it tests it).

Hannes Hirzel wrote:
> Any suggestions why the test
> in https://github.com/hhzl/silk/blob/gh-5/src/Silk-Tests.st
> does not work?
>
> |testDivContainerWithButtons
>      | s |
>
>      s := Silk new DIV: {'id' ->  'container'}.
>      (s BUTTON: 'hello1') on: 'click' bind: [Transcript show: 'Hello1'].
>      (s BUTTON: 'hello2') on: 'click' bind: [Transcript show: 'Hello2'].
>      (s BUTTON: 'hello3') on: 'click' bind: [Transcript show: 'Hello3'].
>
>
>      self assertBodyEndsWith:
>               'div id="fixture">sentinel</div><div id="container"><button>hello1</button><button>hello2</button><button>hello3</button></div>'.
> |
>
> —
> Reply to this email directl
y or view it on GitHub 
> <https://github.com/herby/silk/issues/5#issuecomment-76552257>.
>

**Comment by herby** [comment]
Hannes Hirzel wrote:
>      self assertBodyEndsWith:
>               'div id="fixture">sentinel</div><div id="container"><button>hello1</button><button>hello2</button><button>hello3</button></div>'.

Also, I would not start the assert string with 'div id="fixture"', instead leave it as it is in other tests - so it does not depend on formatting of the fixture div element itself - the presence of the '>' and the sentinel are enough guarantee it is indeed the beginning of it.

**Comment by herby** [comment]
BTW this is not an issue.

**Comment by hhzl** [comment]
Thank you for the feedback!

This now works fine

````
testDivContainerWithButtons
	| s |

	s := '#fixture' asSilk.
	(s BUTTON: 'hello1') on: 'click' bind: [Transcript show: 'Hello1'].
	(s BUTTON: 'hello2') on: 'click' bind: [Transcript show: 'Hello2'].
	(s BUTTON: 'hello3') on: 'click' bind: [Transcript show: 'Hello3'].
	
	self assertBodyEndsWith: '>sentinel<button>hello1</button><button>hello2</button><button>hello3</button></div>'.

````

**Comment by herby** [comment]
Hannes Hirzel wrote:
> Thank you for the feedback!
>
> This now works fine
>
> |testDivContainerWithButtons
>      | s |
>
>      s := '#fixture' asSilk.
>      (s BUTTON: 'hello1') on: 'click' bind: [Transcript show: 'Hello1'].
BTW if you prefer not to parenthesize; this can be achieved alternatively by

  s BUTTON
    << 'hello1';
    on: 'click' bind: [Transcript show: 'Hello1'].

Though I think maybe if this worked if would be even better:

  s BUTTON: { 'hello1'. 'event click' -> [Transcript show: 'Hello1'] }.

**Comment by hhzl** [comment]
In terms of coding style I feel comfortable with

      (s BUTTON: 'hello1') on: 'click' bind: [Transcript show: 'Hello1'].

This is the regular Smalltalk way of writing code. Two keyword
messages. One of them has a block as an argument.

**Comment by hhzl** [comment]
In terms of coding style I feel comfortable with

      (s BUTTON: 'hello1') on: 'click' bind: [Transcript show: 'Hello1'].

This is the regular Smalltalk way of writing code.
Two keyword messages.
One of them has a block as an argument.
